--

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_topology;

CREATE DATABASE semad_car;
CREATE SCHEMA IF NOT EXISTS schema_base;
CREATE SCHEMA IF NOT EXISTS hibernate;
CREATE SCHEMA IF NOT EXISTS domain;



