#Context
server:
  servlet:
    context-path: /
  port: 8087


#Database
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: 'jdbc:oracle:thin:@scan-prod:1521/oramago'
    username: SIGA2_BASE_REFERENCIA_GEO
    password: Guaxupita#SIGA2_BASE
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: oracle
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.oracle.OracleSpatial10gDialect
        default_schema: SIGA2_BASE_REFERENCIA_GEO
        format_sql: true
        spatial:
          connection_finder: br.gov.go.mago.geobasereferencia.config.OracleConnectionFinderConfig

#Logging
logging:
  level:
    br:
      gov.go.mago.geoportalbasereferencia: debug
    org:
      springframework:
        web: debug

#Security
security:
  accessControl:
    allowOrigins: '*, http://localhost:4200, http://localhost:4201, http://localhost:4202, http://localhost:4206, http://localhost:4208, http://geoportal-commons.memora.com.br, http://licenciamento.mago.memora.com.br, http://portal.mago.memora.com.br, http://scorp.mago.memora.com.br, http://arrecadacao.mago.memora.com.br'
  identityService:
    uri: http://api.portal-server-desenv.apps.ocp.mago.go.gov.br

geoserver:
  url: 'http://geo.mago.go.gov.br/geoserver/ows?service=wms'
  authToken: 541085de-9a2e-454e-bdba-eb3d57a2f492

